FROM --platform=$BUILDPLATFORM docker.io/golang:1.21@sha256:4521f9de32e00d8e860a008f5f5fcc98c38e9e80609044aa10fa3fe599bec955 as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/docker:24.0-dind@sha256:39920e7f8b71f33db3d145a1fb1fa8349ae97cc6dd64b738a2b77e9eddbd9999

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-docker-buildx"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-docker-buildx"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-docker-buildx"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-docker-buildx"

ARG TARGETOS
ARG TARGETARCH
ARG BUILDX_VERSION

# renovate: datasource=github-releases depName=docker/buildx
ENV BUILDX_VERSION="${BUILDX_VERSION:-v0.12.0}"

ENV DOCKER_HOST=unix:///var/run/docker.sock

RUN apk --update add --virtual .build-deps curl && \
    apk --update add --no-cache git coredns && \
    apk upgrade --no-cache libcrypto3 libssl3 && \
    mkdir -p /usr/lib/docker/cli-plugins/ && \
    curl -SsL -o /usr/lib/docker/cli-plugins/docker-buildx \
        "https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION##v}/buildx-v${BUILDX_VERSION##v}.${TARGETOS:-linux}-${TARGETARCH:-amd64}" && \
    chmod 755 /usr/lib/docker/cli-plugins/docker-buildx && \
    apk del .build-deps && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/Corefile /etc/coredns/Corefile
COPY --from=build /src/dist/drone-docker-buildx /bin/drone-docker-buildx
ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh", "drone-docker-buildx"]
